image: cfrank0214/whatsthere:latest

pipelines:
  default:
    - step:
        caches:
          - yarncache
        script:
          - yarn
          - yarn test
  branches:
    develop:
     - step:
         name: Publish to expo dev
         deployment: test
         caches:
           - yarncache
         script:
           - yarn
           - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
           - expo publish --non-interactive
    master:
     - step:
         name: Test with Jest
         caches:
           - yarncache
         script:
           - yarn
           - yarn test
     - step:
         name: Deploy to Expo
         trigger: manual
         deployment: production
         caches:
           - yarncache
         script:
           - yarn
           - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
           - expo publish --non-interactive
definitions:
  caches:
    yarncache: /usr/local/share/.cache/yarn/v1