image: cfrank0214/whatsthere:latest

pipelines:
  default:
    - step:
        caches:
          - npmcache
        script:
          - npm i
          - npm test
  branches:
    develop:
     - step:
         name: Publish to expo dev
         deployment: test
         caches:
           - npmcache
         script:
           - npm i
           - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
           - expo publish --non-interactive
    master:
     - step:
         name: Test with Jest
         caches:
           - npmcache
         script:
           - npm
           - npm test
     - step:
         name: Deploy to Expo
         trigger: manual
         deployment: production
         caches:
           - npmcache
         script:
           - npm i
           - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
           - expo publish --non-interactive
           - expo build:ios --non-interactive
definitions:
  caches:
    nmpcache: /usr/local/share/.cache/npm/v1