---
image: tarampampam/node:8.11-jessie
definitions:
  caches:
    npm: ~/.npm
    jest: .jest
pipelines:
  default:
    - step:
        name: Test with Jest
        caches:
          - npm
          - jest
        script:
          - npm ci
          - npx jest --ci
  branches:
    feature:
      - step:
          name: Test feature branch
          caches:
            - npm
            - jest
          script:
            - npm ci
            - npx jest --ci
    master:
      - step:
          name: Test with Jest
          caches:
            - npm
            - jest
          script:
            - npm ci
            - npx jest --ci
      - step:
          name: Deploy to Expo
          trigger: manual
          deployment: production
          caches:
            - npm
            - jest
          script:
            - apk add --no-cache bash
            - npm ci
            - npm install --save-dev expo-cli
            - npx expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD
            - npx expo publish --non-interactive
            - npx expo build:ios --non-interactive
