image: node:8

pipelines:
  default:
    - step:
        caches:
          - yarncache
        script:
          - yarn
          - yarn test
  branches:
    develop:
     - step:
         name: Publish to expo dev
         deployment: test
         caches:
           - yarncache
         script:
           - yarn
           - yarn global add exp
           - exp login -u $EXPO_NAME -p $EXPO_PWD
           - yarn run publish:dev
    master:
     - step:
         name: Publish to expo prod
         deployment: staging
         caches:
           - yarncache
         script:
           - yarn
           - yarn global add exp
           - exp login -u $EXPO_USERNAME -p $EXPO_PASSWORD
           - yarn run publish:prod
definitions:
  caches:
    yarncache: /usr/local/share/.cache/yarn/v1